import type { Metadata } from 'next'
import './globals.css'

import importFont from 'next/font/local'

const font = importFont({
    src: './font.woff2',
    display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
