import type { Metadata } from 'next'
import './globals.css'

import importFont from 'next/font/local'
import BottomNav from '@/components/navigation/bottom-nav'
import Providers from '@/providers'
import { cn } from '@/lib/utils/css'

const font = importFont({
  src: './font.woff2',
  display: 'swap',
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(font.variable, 'font-sans')}>
        <Providers>
          {children}
          <BottomNav />
        </Providers>
      </body>
    </html>
  )
}
